In [100]:
s=input()

k = []
for x in s:
    if x not in 'AEIOUaeiou':
        print(x, end = '')

 Upgrad


pgrd

In [8]:
import numpy as np
a = np.array([[9,3,2],[4, 0, 1],[5,8, 6]])
#b= np.array([[10, 30, 20], [60, 40, 50]])
a

array([[9, 3, 2],
       [4, 0, 1],
       [5, 8, 6]])

In [9]:
b = np.argsort(a)
b


array([[2, 1, 0],
       [1, 2, 0],
       [0, 2, 1]], dtype=int64)

In [1]:
a

NameError: name 'a' is not defined

In [12]:
import numpy as np
list_1 = [3,2,1,6,5,4]
a= np.array(list_1)
a

array([3, 2, 1, 6, 5, 4])

In [13]:
np.argsort(a)

array([2, 1, 0, 5, 4, 3], dtype=int64)

In [4]:
import numpy as np
a = np.array([[9,3,2],[4, 0, 1],[5,8, 6]])
b = np.argsort(a[:,0])
b

array([1, 2, 0], dtype=int64)

In [21]:
a = np.array([[9,3,2],[4, 0, 1],[5,8, 6]])
a

array([[9, 3, 2],
       [4, 0, 1],
       [5, 8, 6]])

In [5]:
np.take_along_axis(a,b,axis=0)

ValueError: `indices` and `arr` must have the same number of dimensions

In [73]:
import numpy as np
a = np.array([[9, 3, 2], [4, 0, 1], [5, 8, 6]])



[9 3 2]


In [58]:
np.sort(a,axis = 1)

array([[2, 3, 9],
       [0, 1, 4],
       [5, 6, 8]])

In [50]:
np.argsort(a)

array([[2, 1, 0],
       [1, 2, 0],
       [0, 2, 1]], dtype=int64)

In [54]:
np.partition(a,2)

array([[2, 3, 9],
       [0, 1, 4],
       [5, 6, 8]])